### ISSUE TITLE
graphics does not apear in card

### ISSUE THREAD

**Issue by smartdomus-pt** [tdvtdv/ha-tdv-bar#20]
Graphics does not apear in the card, but apears in the edit mode demo. PC and Android

![graphs](https://github.com/tdvtdv/ha-tdv-bar/assets/142928818/89aec601-7db5-42a3-bdad-d837c8a80be0)
![prog](https://github.com/tdvtdv/ha-tdv-bar/assets/142928818/ed97005e-2a90-4692-89f5-e2eee6703518)

**Comment by brunoz78** [comment]
I have exactly the same problem. Tested in Chrome and Edge (Windows 10) as well as in the Android app from HA.
Has only been since the update to HA 2024.7.x

**Comment by sfortis** [comment]
same issue here / Edge windows 11 / android

**Comment by bey0099** [comment]
I have the same issue

**Comment by Barrus1** [comment]
Hi,

I have the same issue, but graphes are Ok when i edit config.
![image](https://github.com/user-attachments/assets/2a2b2072-9441-4355-b6f7-0b4d7b8e71be)
![image](https://github.com/user-attachments/assets/3c75b80b-d56d-4b5d-8d90-962fb85d9e3a)

**Comment by kdutton1964** [comment]
Well, it looks like good news on my end at least. I am on the newest version I believe of all apps. The card now is rendering correctly on Mac OS X, iPad, iPhone, and android tablet. This is with native apps from Home Assistant and in Safari on all applicable devices. Thank you.

**Comment by tdvtdv** [comment]
The problem has been fixed in version 1.2.3

**Comment by NoXPhasma** [comment]
> The problem has been fixed in version 1.2.3

Unfortunately, it is not. I still have the same behavior with 1.2.3. This is happening in the Android app and the browser. Already tried to redownload the plugin, reload cache and restart HA several times.
