### ISSUE TITLE
Looks wrong in Chrome on the desktop

### ISSUE THREAD

**Issue by ssorgatem** [tdvtdv/ha-tdv-bar#3]
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/108138/e68c174d-d921-4794-8be2-b16df3cfaabb)

But when i edit it it looks good:

![image](https://github.com/tdvtdv/ha-tdv-bar/assets/108138/6c3c674e-9979-41fc-9ef4-062f41916ed5)

It also shows OK on the app

**Comment by tdvtdv** [comment]
Are such rendering problems only in edit mode or in normal operation too?

**Comment by ssorgatem** [comment]
I just tested it, and it only seems to happen in edit mode

**Comment by diegoooo82** [comment]
i have the same problem in chrome
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/336755/db012f6d-32e9-4d75-a8ba-213344071f6f)

in firefox work fine
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/336755/1281d424-12d5-4262-8ab6-d7184dac115d)

i try ti clean cache and update chrome at latest version 122.0.6261.95

**Comment by Tozapid** [comment]
The same problem in the iOS app 
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/9052342/b1fcf10f-4469-4701-add9-32bdfd1c1043)

and yes, same issue in chrome

**Comment by tdvtdv** [comment]
This problem should be fixed in the latest release (1.1.7)

**Comment by Tozapid** [comment]
Hm, it looks right in Chrome for now, but I still have problems with Safari and an app on my iPhone

**Comment by computerfreek274** [comment]
Does not work in iOS still and will not cast to a Chromecast

**Comment by fernandeusto** [comment]
similar problem

![imagen](https://github.com/tdvtdv/ha-tdv-bar/assets/87156183/874d9609-62a1-43a0-afd0-ef6dbc64622f)
bad on view panel

![imagen](https://github.com/tdvtdv/ha-tdv-bar/assets/87156183/191acdbf-6b56-4613-9614-b55aaf986d31)
good on edit panel

**Comment by trueKAMi** [comment]
Same problem here.
Looks wrong in HA app and Chrome, but fine in edit mode:
Normal chrome:
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/1610865/387aa80a-1755-4b5f-93d5-c5fb1aba4c2f)

Edit mode:
![image](https://github.com/tdvtdv/ha-tdv-bar/assets/1610865/bd9f5c67-5e05-4858-8806-4d4bcc202ec2)

Core  2024.7.1
Supervisor  2024.06.2
Operating System  12.4
Frontend  20240705.0
Chrome Version 126.0.6478.127

Default theme, frontend mods installed via HACS that may influence things:
layout-card
Slider Button Card
apexcharts-card

If more info is needed, please let me know :)

**Comment by reganerasmus** [comment]
It doesnt look like anyone is fixing this issue

**Comment by Lars-Hiller** [comment]
I am also facing the same issue - both in the Edge browser (Version 129.0.2792.52) as well as the Android Companion App (Pixel 7 pro with latest Android and HA versions).

Working fine during config, but not corretly shown in normal dashboard.

![Screenshot 2024-09-26 153818](https://github.com/user-attachments/assets/20e06c0f-740a-4f8e-8651-8d4a298d8089)
![Screenshot 2024-09-26 153828](https://github.com/user-attachments/assets/576c7ab5-e5a1-42a6-9e68-8b5e3215f9af)

**Comment by raoulteeuwen** [comment]
Can everyone with this problem test the following: make the card position 1 on the tab it is on. Play around with positioning the card through the + and - around the position nr. So move around the card from the top / to be the 1st card, and see when the rendering breaks. With my config, i can sometimes move one of these cards to position 5, but beyond, the rendering breaks and also often when i return it is broken. It only seems happy with being the nr 1 card on a tab. Tried in private mode and on mobile (HA app): same problem.

**Comment by Lars-Hiller** [comment]
> Can everyone with this problem test the following: make the card position 1 on the tab it is on. Play around with positioning the card through the + and - around the position nr. So move around the card from the top / to be the 1st card, and see when the rendering breaks. With my config, i can sometimes move one of these cards to position 5, but beyond, the rendering breaks and also often when i return it is broken. It only seems happy with being the nr 1 card on a tab. Tried in private mode and on mobile (HA app): same problem.

I started in position 6, stepping down to 1:
6 - broken in Edge Browser - broken in Andoid app
5 - broken in Edge Browser - broken in Andoid app
4 - broken in Edge Browser - broken in Andoid app
3 - broken in Edge Browser - broken in Andoid app
2 - WORKING in Edge Browser - broken in Andoid app
1 - WORKING in Edge Browser - WORKING in Andoid app

**Comment by reganerasmus** [comment]
thanks, i just moved this card to position 1 and it works fine.

**Comment by MrFr33man123** [comment]
![image](https://github.com/user-attachments/assets/832a188e-1ef4-4b16-89a9-b47f6210026d)
TDV 1.2.3
TDV Last Working 1.2.1

````
type: custom:tdv-bar-card
title: Energy consumers
scaletype: log10
rangemax: 800
histmode: 1
trackingmode: 4
trackingvalue: max
colors:
  chart_bg: "#00000040"
  frame: "#FFFFFF30"
  bar: "#0090FF"
entities:
  - entity: sensor.schaffner_p_ac
    icon: mdi:solar-panel
    name: Schaffner
    barcolor: "#808000"
  - entity: sensor.solar_wechselrichter_current_power
    state: switch.solar_wechselrichter
    icon: mdi:solar-panel
    name: P110
    barcolor: "#B0B000"
  - entity: sensor.waschmachine_current_consumption
    icon: mdi:washing-machine
    name: Waschmachine
    state: switch.waschmachine
  - entity: sensor.hildegard_current_consumption
    icon: mdi:laptop-account
    name: Hildegard
    state: switch.hildegard
  - entity: sensor.manfred_current_consumption
    icon: mdi:server-network
    name: IOT
  - entity: sensor.pc_tisch_current_consumption
    name: Pc Tisch
    icon: mdi:desktop-tower-monitor
  - entity: sensor.fusbodenpumpe_current_power
    name: Fußboden Pumpe
    icon: mdi:pump
    state: switch.fusbodenpumpe
```

**Comment by raoulteeuwen** [comment]
@tdvtdv Is that 'position the card as 1st card on the tab and it seems to work' something that helps troubleshoot the problem?

**Comment by gabriele-latino** [comment]
Same issue for me, is there a chance it will get fixed?

**Comment by tdvtdv** [comment]
Of course there's a chance. For now, you can try to use the previous version.
So far I can't understand why the browser sometimes doesn't want to give the correct card size :(

**Comment by ppuschmann** [comment]
> Of course there's a chance. For now, you can try to use the previous version.

Which version?

**Comment by tdvtdv** [comment]
Please check how it works in the latest (v2.0.1) version
